// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVBDkD3VptaNNGxi2V4wHlQzv6LnAByDs',
    appId: '1:2749148729:web:da4c84869cdd389f8ce7e8',
    messagingSenderId: '2749148729',
    projectId: 'crudoperation-629a5',
    authDomain: 'crudoperation-629a5.firebaseapp.com',
    storageBucket: 'crudoperation-629a5.appspot.com',
    measurementId: 'G-8HZXJXZ9GJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1V305gCNunGwX65NRhGU8qrKMQadEiDo',
    appId: '1:2749148729:android:f255135ca62010fc8ce7e8',
    messagingSenderId: '2749148729',
    projectId: 'crudoperation-629a5',
    storageBucket: 'crudoperation-629a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLI_S1pMbPjH_pg0n4ZVmh_t0QTmNo4sc',
    appId: '1:2749148729:ios:5e413d1aea6bb9e28ce7e8',
    messagingSenderId: '2749148729',
    projectId: 'crudoperation-629a5',
    storageBucket: 'crudoperation-629a5.appspot.com',
    iosClientId: '2749148729-9d0pg8pdbo95dk7ha7i2oouc2hdkug79.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudOpert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLI_S1pMbPjH_pg0n4ZVmh_t0QTmNo4sc',
    appId: '1:2749148729:ios:5e413d1aea6bb9e28ce7e8',
    messagingSenderId: '2749148729',
    projectId: 'crudoperation-629a5',
    storageBucket: 'crudoperation-629a5.appspot.com',
    iosClientId: '2749148729-9d0pg8pdbo95dk7ha7i2oouc2hdkug79.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudOpert',
  );
}
